name: Build and publish docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [Dockerfile]

concurrency: publish

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          platforms: |
            linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
          outputs: type=image,oci-mediatypes=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
